name: "checkout-ns3"
description: "Checkout this repository as ns-3 module"

# Requires wget!

runs:
  using: "composite"
  steps:
    - name: "Checkout supported ns-3 version"
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          NS3-VERSION
        sparse-checkout-cone-mode: false
    - name: "Download ns-3-dev working tree with Gitlab API"
      run: |
        tag=$(< NS3-VERSION) && tag=${tag#release }
        wget -nv -O ns-3-dev.tar https://gitlab.com/api/v4/projects/nsnam%2Fns-3-dev/repository/archive.tar?sha=$tag
        tar -xf ns-3-dev.tar && cp -a ns-3-dev-$tag-*/. . && rm -R ns-3-dev.tar ns-3-dev-$tag*
      shell: bash
    - name: "Checkout this repository as ns-3 module"
      uses: actions/checkout@v4
      with:
        path: "src/lorawan"
