name: "Per-commit ns-3 CI jobs"
run-name: "Per-commit"

on: [push, pull_request]

jobs:
  # .pre stage
  code-linting:
    uses: ./.github/workflows/.code-linting.yml

  # build and test
  per-commit:
    needs: code-linting
    strategy:
      matrix:
        compiler: [g++]
        mode: [default]
        test: [true]
        include:
          - compiler: g++
            mode: debug
    uses: ./.github/workflows/.base-per-commit.yml
    with:
      compiler: ${{ matrix.compiler }}
      mode: ${{ matrix.mode }}
      extra_options: ${{ matrix.extra_options }}
      test: ${{ matrix.test }}

  # documentation
  documentation:
    uses: ./.github/workflows/.doc.yml
    needs: per-commit
