name: "Per-commit ns-3 CI jobs"
run-name: "Per-commit"

on: [push, pull_request]

jobs:
  # pre-build
  pre-build:
    uses: ./.github/workflows/.code-linting.yml
    with:
      stage: pre-build

  # build and test
  build:
    needs: pre-build
    strategy:
      matrix:
        compiler: [g++]
        mode: [default, optimized]
        do_test: [test]
        include:
          - compiler: g++
            mode: debug
    uses: ./.github/workflows/.base-per-commit.yml
    with:
      compiler: ${{ matrix.compiler }}
      mode: ${{ matrix.mode }}
      extra_options: ${{ matrix.extra_options }}
      do_test: ${{ matrix.do_test }}

  # documentation
  documentation:
    uses: ./.github/workflows/.doc.yml
    needs: build
